stages:
  process:
    cmd: python src/engineering/process.py --raw 'data/raw/dq_recsys_challenge_2025(in).csv'
      --process data/processed/processed_fnb.csv
    deps:
    - data/raw/dq_recsys_challenge_2025(in).csv
    - src/engineering/process.py
    outs:
    - data/processed/processed_fnb.csv
  feature:
    cmd: python src/engineering/feature.py --process data/processed/processed_fnb.csv
      --train data/training/train.csv --test data/training/test.csv
    deps:
    - data/processed/processed_fnb.csv
    - src/engineering/feature.py
    outs:
    - data/training/test.csv
    - data/training/train.csv
  trainer:
    cmd: python src/training/run_trainer.py --data-path data/training/train.csv --output
      models/classifier
    deps:
    - data/training/train.csv
    - src/training/run_trainer.py
    params:
    - src/training/model.params.yml:
      - train.mode
      - train.model
    outs:
    - models/classifier
